"""Initial migration

Revision ID: 08e18b3b4522
Revises:
Create Date: 2026-04-06 01:59:50.091624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "08e18b3b4522"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("themes", sa.JSON(), nullable=True),
        sa.Column("skills_detected", sa.JSON(), nullable=True),
        sa.Column("values_detected", sa.JSON(), nullable=True),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("perception_signals", sa.JSON(), nullable=True),
        sa.Column("raw_output", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["inputentry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branddna",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("positioning", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("niche", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("voice", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=True),
        sa.Column("content_pillars", sa.JSON(), nullable=True),
        sa.Column("credibility_score", sa.Integer(), nullable=True),
        sa.Column("gap_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entries_analyzed", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credibilityreport",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_of", sa.DateTime(), nullable=False),
        sa.Column("alignment_score", sa.Integer(), nullable=False),
        sa.Column("aligned_moments", sa.JSON(), nullable=True),
        sa.Column("misaligned_moments", sa.JSON(), nullable=True),
        sa.Column("values_checked", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "desiredbrandstatement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("legacy_words", sa.JSON(), nullable=True),
        sa.Column(
            "desired_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("reverse_engineered_actions", sa.JSON(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inputentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "JOURNAL", "PULSE", "DEBRIEF", "NETWORK", "REVIEW", name="inputmode"
            ),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("context_tags", sa.JSON(), nullable=True),
        sa.Column(
            "emotion",
            sa.Enum("ENERGIZED", "NEUTRAL", "DRAINED", name="emotion"),
            nullable=True,
        ),
        sa.Column("alignment_score", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_analyzed", sa.Boolean(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "networklog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "contact_type",
            sa.Enum(
                "DECISION_MAKER", "INFO_SOURCE", "SUPPORTER", name="networkcontacttype"
            ),
            nullable=False,
        ),
        sa.Column("context", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("value_given", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("value_received", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("follow_up_needed", sa.Boolean(), nullable=False),
        sa.Column("logged_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "perceptionreport",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "self_description_summary",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "perceived_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("gap_analysis", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entries_analyzed", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "valueitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "personal_context", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("declared_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "voicesample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "generatedcontent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_entry_id", sa.Integer(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum(
                "LINKEDIN_POST",
                "TWITTER_THREAD",
                "BIO_SHORT",
                "BIO_LONG",
                "ELEVATOR_PITCH_30S",
                "ELEVATOR_PITCH_60S",
                name="contentplatform",
            ),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_entry_id"],
            ["inputentry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("generatedcontent")
    op.drop_table("voicesample")
    op.drop_table("valueitem")
    op.drop_table("perceptionreport")
    op.drop_table("networklog")
    op.drop_table("inputentry")
    op.drop_table("desiredbrandstatement")
    op.drop_table("credibilityreport")
    op.drop_table("branddna")
    op.drop_table("analysis")
    # ### end Alembic commands ###
